<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="6" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-11T15:56:32 IST" name="Suite" finished-at="2024-11-11T15:58:35 IST" duration-ms="122886">
    <groups>
    </groups>
    <test started-at="2024-11-11T15:56:32 IST" name="Test" finished-at="2024-11-11T15:58:35 IST" duration-ms="122886">
      <class name="HomePage.LoginSignUpFunctionality">
        <test-method signature="Login()[pri:0, instance:HomePage.LoginSignUpFunctionality@54bff557]" started-at="2024-11-11T15:56:32 IST" name="Login" finished-at="2024-11-11T15:56:48 IST" duration-ms="16277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="invalidcredentials()[pri:0, instance:HomePage.LoginSignUpFunctionality@54bff557]" started-at="2024-11-11T15:56:48 IST" name="invalidcredentials" finished-at="2024-11-11T15:57:00 IST" duration-ms="11643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidcredentials -->
        <test-method signature="logout()[pri:0, instance:HomePage.LoginSignUpFunctionality@54bff557]" started-at="2024-11-11T15:57:00 IST" name="logout" finished-at="2024-11-11T15:57:13 IST" duration-ms="13441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- HomePage.LoginSignUpFunctionality -->
      <class name="HomePage.BasicAuthentication">
        <test-method signature="Authenction()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:57:13 IST" name="Authenction" finished-at="2024-11-11T15:57:28 IST" duration-ms="14785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Authenction -->
        <test-method signature="LinkBrokenTest()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:57:28 IST" name="LinkBrokenTest" finished-at="2024-11-11T15:57:36 IST" duration-ms="7826" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at HomePage.BasicAuthentication.LinkBrokenTest(BasicAuthentication.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LinkBrokenTest -->
        <test-method signature="SlowNetworkSpeed()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:57:36 IST" name="SlowNetworkSpeed" finished-at="2024-11-11T15:58:00 IST" duration-ms="24728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SlowNetworkSpeed -->
        <test-method signature="geoLocation()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:58:00 IST" name="geoLocation" finished-at="2024-11-11T15:58:15 IST" duration-ms="14534" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Fərq edin] but found [Make a difference]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Fərq edin] but found [Make a difference]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at HomePage.BasicAuthentication.geoLocation(BasicAuthentication.java:119)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- geoLocation -->
        <test-method signature="mobileEmulate()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:58:15 IST" name="mobileEmulate" finished-at="2024-11-11T15:58:25 IST" duration-ms="10477" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mobileEmulate -->
        <test-method signature="titleVerification()[pri:0, instance:HomePage.BasicAuthentication@66f57048]" started-at="2024-11-11T15:58:25 IST" name="titleVerification" finished-at="2024-11-11T15:58:35 IST" duration-ms="9065" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign Up] but found [Maanch | Trust. Technology. Traction.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign Up] but found [Maanch | Trust. Technology. Traction.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at HomePage.BasicAuthentication.titleVerification(BasicAuthentication.java:97)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleVerification -->
      </class> <!-- HomePage.BasicAuthentication -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
